"""initial schema

Revision ID: 7098b5331f5d
Revises: 
Create Date: 2026-06-29 14:30:50.419367
"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7098b5331f5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('backup_type', sa.Enum('manual', 'scheduled', 'pre_update', name='backuptype', native_enum=False, length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_backup_type'), ['backup_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_backups_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Enum('desktop', 'email', 'slack', 'discord', 'telegram', 'webhook', name='notificationchannel', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='notificationseverity', native_enum=False, length=32), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_error', sa.String(length=500), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_sent'), ['is_sent'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_severity'), ['severity'], unique=False)

    op.create_table('providers',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('plugin', sa.String(length=80), nullable=False),
    sa.Column('api_format', sa.Enum('openai', 'anthropic', 'gemini', 'ollama', 'azure_openai', 'custom', name='apiformat', native_enum=False, length=32), nullable=False),
    sa.Column('auth_type', sa.Enum('bearer', 'query_param', 'header', 'oauth', 'none', name='authtype', native_enum=False, length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('default_model', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('enabled', 'disabled', 'offline', 'maintenance', name='providerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('extra_headers', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_providers_plugin'), ['plugin'], unique=False)
        batch_op.create_index(batch_op.f('ix_providers_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_providers_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_providers_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('profile', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_settings_profile'), ['profile'], unique=False)

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'viewer', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_keys',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('encrypted_key', sa.String(length=2048), nullable=False),
    sa.Column('key_hint', sa.String(length=64), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'cooldown', 'disabled', 'invalid', 'expired', 'quota_reached', 'unknown', name='keystatus', native_enum=False, length=32), nullable=False),
    sa.Column('health_status', sa.Enum('healthy', 'degraded', 'unhealthy', 'offline', 'unknown', name='healthstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_cooldown_until'), ['cooldown_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_health_status'), ['health_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_status'), ['status'], unique=False)

    op.create_table('models',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_embeddings', sa.Boolean(), nullable=False),
    sa.Column('supports_images', sa.Boolean(), nullable=False),
    sa.Column('input_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('output_cost_per_1k', sa.Float(), nullable=False),
    sa.Column('task_types', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_provider_id'), ['provider_id'], unique=False)

    op.create_table('health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('check_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'unhealthy', 'offline', 'unknown', name='healthstatus', native_enum=False, length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_logs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_logs_success'), ['success'], unique=False)

    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_logs_success'), ['success'], unique=False)

    op.create_table('statistics',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window', sa.Enum('hour', 'day', 'week', 'month', 'year', name='statisticwindow', native_enum=False, length=32), nullable=False),
    sa.Column('bucket', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('max_latency_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statistics_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statistics_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_statistics_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statistics_window'), ['window'], unique=False)

    # Seed default providers
    providers_table = sa.table(
        'providers',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('description', sa.String),
        sa.column('plugin', sa.String),
        sa.column('api_format', sa.String),
        sa.column('auth_type', sa.String),
        sa.column('base_url', sa.String),
        sa.column('default_model', sa.String),
        sa.column('status', sa.String),
        sa.column('is_enabled', sa.Boolean),
        sa.column('priority', sa.Integer),
        sa.column('config', sa.JSON),
        sa.column('extra_headers', sa.JSON),
    )
    
    op.bulk_insert(
        providers_table,
        [
            {
                "id": 1,
                "name": "OpenAI",
                "slug": "openai",
                "description": "Official OpenAI provider integration.",
                "plugin": "openai",
                "api_format": "openai",
                "auth_type": "bearer",
                "base_url": "https://api.openai.com/v1",
                "default_model": "gpt-4o",
                "status": "enabled",
                "is_enabled": True,
                "priority": 1,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 2,
                "name": "Anthropic",
                "slug": "anthropic",
                "description": "Official Anthropic Claude provider integration.",
                "plugin": "anthropic",
                "api_format": "anthropic",
                "auth_type": "header",
                "base_url": "https://api.anthropic.com",
                "default_model": "claude-3-5-sonnet-20241022",
                "status": "enabled",
                "is_enabled": True,
                "priority": 2,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 3,
                "name": "Gemini",
                "slug": "gemini",
                "description": "Google Gemini API provider integration.",
                "plugin": "gemini",
                "api_format": "gemini",
                "auth_type": "query_param",
                "base_url": "https://generativelanguage.googleapis.com/v1beta",
                "default_model": "gemini-1.5-pro",
                "status": "enabled",
                "is_enabled": True,
                "priority": 3,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 4,
                "name": "DeepSeek",
                "slug": "deepseek",
                "description": "DeepSeek AI provider integration.",
                "plugin": "openai",
                "api_format": "openai",
                "auth_type": "bearer",
                "base_url": "https://api.deepseek.com/v1",
                "default_model": "deepseek-chat",
                "status": "enabled",
                "is_enabled": True,
                "priority": 4,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 5,
                "name": "Grok",
                "slug": "grok",
                "description": "xAI Grok provider integration.",
                "plugin": "openai",
                "api_format": "openai",
                "auth_type": "bearer",
                "base_url": "https://api.x.ai/v1",
                "default_model": "grok-beta",
                "status": "enabled",
                "is_enabled": True,
                "priority": 5,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 6,
                "name": "OpenRouter",
                "slug": "openrouter",
                "description": "OpenRouter LLM aggregation interface.",
                "plugin": "openai",
                "api_format": "openai",
                "auth_type": "bearer",
                "base_url": "https://openrouter.ai/api/v1",
                "default_model": "meta-llama/llama-3.1-70b-instruct",
                "status": "enabled",
                "is_enabled": True,
                "priority": 6,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 7,
                "name": "Ollama",
                "slug": "ollama",
                "description": "Local Ollama model runner instance.",
                "plugin": "ollama",
                "api_format": "openai",
                "auth_type": "none",
                "base_url": "http://localhost:11434/v1",
                "default_model": "llama3",
                "status": "enabled",
                "is_enabled": True,
                "priority": 7,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 8,
                "name": "Aerolink Claude",
                "slug": "aerolink-claude",
                "description": "Aerolink Claude proxy interface.",
                "plugin": "anthropic",
                "api_format": "anthropic",
                "auth_type": "header",
                "base_url": "https://capi.aerolink.lat/",
                "default_model": "claude-3-5-sonnet-20241022",
                "status": "enabled",
                "is_enabled": True,
                "priority": 8,
                "config": {},
                "extra_headers": {},
            },
            {
                "id": 9,
                "name": "Aeronat Claude",
                "slug": "aeronat-claude",
                "description": "Aeronat Claude proxy interface.",
                "plugin": "anthropic",
                "api_format": "anthropic",
                "auth_type": "header",
                "base_url": "https://aeronat.lab/",
                "default_model": "claude-3-5-sonnet-20241022",
                "status": "enabled",
                "is_enabled": True,
                "priority": 9,
                "config": {},
                "extra_headers": {},
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statistics_window'))
        batch_op.drop_index(batch_op.f('ix_statistics_provider_id'))
        batch_op.drop_index(batch_op.f('ix_statistics_bucket'))
        batch_op.drop_index(batch_op.f('ix_statistics_api_key_id'))

    op.drop_table('statistics')
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_logs_success'))
        batch_op.drop_index(batch_op.f('ix_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_request_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_request_logs_model'))
        batch_op.drop_index(batch_op.f('ix_request_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_request_logs_api_key_id'))

    op.drop_table('request_logs')
    with op.batch_alter_table('health_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_logs_success'))
        batch_op.drop_index(batch_op.f('ix_health_logs_status'))
        batch_op.drop_index(batch_op.f('ix_health_logs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_health_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_health_logs_api_key_id'))

    op.drop_table('health_logs')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_provider_id'))
        batch_op.drop_index(batch_op.f('ix_models_name'))
        batch_op.drop_index(batch_op.f('ix_models_is_enabled'))

    op.drop_table('models')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_status'))
        batch_op.drop_index(batch_op.f('ix_api_keys_provider_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_priority'))
        batch_op.drop_index(batch_op.f('ix_api_keys_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_api_keys_health_status'))
        batch_op.drop_index(batch_op.f('ix_api_keys_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_api_keys_cooldown_until'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_profile'))
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_index(batch_op.f('ix_settings_group'))

    op.drop_table('settings')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_status'))
        batch_op.drop_index(batch_op.f('ix_providers_slug'))
        batch_op.drop_index(batch_op.f('ix_providers_priority'))
        batch_op.drop_index(batch_op.f('ix_providers_plugin'))
        batch_op.drop_index(batch_op.f('ix_providers_is_enabled'))

    op.drop_table('providers')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_severity'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_sent'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_event_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_channel'))

    op.drop_table('notifications')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_created_at'))
        batch_op.drop_index(batch_op.f('ix_backups_backup_type'))

    op.drop_table('backups')
    # ### end Alembic commands ###
